
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Debug npm and node versions
        run: |
          npm --version
          node --version

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install --legacy-peer-deps --force
        env:
          CI: true

      - name: Debug Installed Packages
        run: |
          echo "Listing installed packages:"
          npm list @react-three/fiber @react-three/drei three || true
          
      - name: Build
        run: |
          echo "Building with GITHUB_PAGES=true"
          export GITHUB_PAGES=true
          npm run build
        env:
          GITHUB_PAGES: true
          PUBLIC_URL: "/aj-portfolio"
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Debug Build Output
        run: |
          echo "Contents of dist directory:"
          ls -la dist

      - name: Create .nojekyll file
        run: |
          touch dist/.nojekyll

      - name: Copy 404.html to dist
        run: |
          cp public/404.html dist/404.html
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
